"""Source-backed research hypotheses; none is an approval for live trading."""

CATALOG = {
    "as_of": "2026-10-01",
    "summary": (
        "Amaç piyasanın bilgi işleme, fon akışı ve likidite mekanizmalarından doğabilecek "
        "avantajları ölçmektir. Buradaki kaynaklar ekonomik gerekçe sağlar; günümüz BIST'inde "
        "maliyet sonrası kazanç kanıtı sağlamaz. Laboratuvarın üç sabit, yalnız uzun pozisyon "
        "kuralı araştırma hipotezidir. Sonuçlar geçmiş fiyat simülasyonudur; canlı işlem onayı değildir. "
        "Başarı oranı tek başına yeterli değildir: aynı tarihlerde endekse göre fark, maliyet "
        "dayanıklılığı, bağımsız örnek sayısı ve başarısız dönemler birlikte okunmalıdır."
    ),
    "hypotheses": [
        {
            "id": "relative_momentum",
            "title": "Maliyet sonrası göreli momentum",
            "priority": 1,
            "mechanism": "Bilginin yavaş işlenmesi veya kademeli portföy değişimleri göreli güçlü paylarda devamlılık yaratabilir. Endeksten ayrışma ile genel piyasa yükselişini ayırmak gerekir.",
            "evidence": "AQR'nin 19 gelişmiş piyasadaki tarihsel gerçek işlemler araştırması momentumun maliyet optimizasyonundan yararlanabildiğini gösterir. Daniel–Moskowitz sert piyasa toparlanmalarında momentum çöküşlerini belgeler. Buradaki basit uzun pozisyon kuralı bu akademik portföylerin replikasyonu değildir.",
            "required_data": ["Aynı tarihlere hizalı pay ve endeks OHLCV", "Temettü/bölünme düzeltmeleri ve tarihsel evren", "Spread, kayma, işlem tutarı ve kapasite"],
            "available": "Günlük OHLCV ile araştırma",
            "falsifier": "Ayrılmış son dönemde endekse göre net fark sıfırın altına düşerse, iki kat maliyette kaybolursa veya birkaç olağandışı işleme dayanırsa avantaj iddiası reddedilir.",
            "next_step": "Sabit kuralı ertesi açılışta girişle sınayıp düşüş, toparlanma ve yatay dönemleri ayrı incele; sonuç görülünce eşikleri yeniden ayarlama.",
            "sources": ["trading_costs", "momentum_crashes"],
        },
        {
            "id": "trend_pullback",
            "title": "Trend içinde geri çekilme",
            "priority": 2,
            "mechanism": "Güçlü eğilim içindeki geçici satış baskısının ardından devamlılık olabileceği sınanır. Düşen bir fiyatın ucuzladığı varsayılmaz; şirket haberleri geçici baskı ile kalıcı değer kaybını ayırabilir.",
            "evidence": "Bu giriş kuralı keşif amaçlı mühendislik hipotezidir. Atıf yapılan araştırma bu kuralı doğrulamaz; kısa vadeli dönüş stratejilerinin işlem maliyetlerine duyarlı olduğunu göstererek karşı kanıt sağlar.",
            "required_data": ["Tamamlanmış günlük fiyatlar ve hacim", "Haber ve kurumsal işlem zamanları", "Gerçekçi alış/satış maliyeti"],
            "available": "Günlük OHLCV ile araştırma",
            "falsifier": "Net getiri veya aynı dönem endeks farkı maliyet stresi altında kaybolursa; zararlar yeni temel bilgi açıklamalarında yoğunlaşırsa kural reddedilir.",
            "next_step": "Sabit koşullar ve ertesi açılış girişiyle araştır; olay verisi gelene kadar haber kaynaklı düşüşleri güvenilir biçimde ayırabildiğini iddia etme.",
            "sources": ["trading_costs"],
        },
        {
            "id": "volume_breakout",
            "title": "Hacim eşlik eden fiyat kırılması",
            "priority": 3,
            "mechanism": "Önceki fiyat bölgesinin artan katılımla aşılmasının devamlılık taşıyabileceği araştırılır. Günlük toplam hacim, alıcı kimliği veya net kurumsal para girişi değildir.",
            "evidence": "Sabit kırılma kuralımız deneysel bir sezgiseldir; doğrulanmış bir makalenin replikasyonu değildir. Emir defteri araştırması fiyat hareketinde likidite boşluklarının önemini gösterir; yüksek hacmin tek başına yön veya kalıcılık kanıtı olmadığını hatırlatır.",
            "required_data": ["Önceki tamamlanmış barlardan fiyat/hacim eşikleri", "Ertesi açılış fiyatı", "Spread, derinlik ve gerçekleşebilirlik"],
            "available": "Günlük OHLCV ile araştırma",
            "falsifier": "Açılış boşluğu avantajı tüketirse, başarısız kırılmaların kaybı kazananları aşarsa veya spread/kayma sonrası endeks farkı kalmazsa hipotez reddedilir.",
            "next_step": "Üç önceden tanımlı kuralın tamamıyla birlikte raporla; sadece en iyi görünen sonucu seçerek başarı ilan etme.",
            "sources": ["liquidity_gaps", "trading_costs"],
        },
        {
            "id": "kap_surprise_drift",
            "title": "KAP sürprizi ve gecikmiş fiyat tepkisi",
            "priority": 4,
            "mechanism": "Açıklanan sonucun önceden bilinen beklentiden farkı ile ilk fiyat tepkisi karşılaştırılır. Sınırlı yatırımcı dikkati bazı bilgilerin fiyatlara geç yansımasına yol açabilir.",
            "evidence": "DellaVigna–Pollet, 1995–2006 örnekleminde cuma bilanço açıklamalarında daha zayıf ilk tepki ve daha güçlü gecikmiş tepki bulur. Bu tarihsel yabancı piyasa bulgusu BIST için cuma al kuralı veya bugünkü kazanç kanıtı değildir.",
            "required_data": ["KAP ilk yayın saati ve orijinal sürüm", "Açıklamadan önce mevcut beklenti veya etiketlenmiş vekili", "İlk işlem yapılabilir fiyat ve sektör getirisi"],
            "available": "Veri bağlantısı eksik",
            "falsifier": "Yayın zamanı, ilk tepki ve likidite kontrolünden sonra gecikmiş net fark yoksa; sinyal yalnız sonradan düzeltilmiş raporlarla çalışıyorsa reddedilir.",
            "next_step": "Önce sürümlü olay veri seti oluştur; beklenti verisi yokken haber duyarlılığını bilanço sürprizi olarak sunma.",
            "sources": ["earnings_attention"],
        },
        {
            "id": "index_flow",
            "title": "Endeks değişikliği ve mekanik fon akışı",
            "priority": 5,
            "mechanism": "Endeks izleyen portföylerin yeniden dengelenmesi geçici arz/talep baskısı oluşturabilir. Potansiyel akış, payın normal işlem tutarına oranlanmalıdır.",
            "evidence": "BIST resmî dönemsel takvimi duyuru ve uygulama dönemlerini tanımlar. Greenwood–Sammon S&P 500 endeks etkisinin zamanla küçüldüğünü gösterir: mekanizma bilindikçe avantaj aşınabilir. Yabancı piyasa sonucu BIST büyüklüğü değildir.",
            "required_data": ["İlk duyuru ve yürürlük zamanları", "Eski/yeni ağırlıklar ve fiili dolaşım", "İzleyici fon büyüklüğü ve pay likiditesi"],
            "available": "Veri bağlantısı eksik",
            "falsifier": "Fiyat hareketi duyurudan önce bitmişse, erişilebilir girişte net fark yoksa veya beklenen akış önemsizse hipotez reddedilir.",
            "next_step": "Resmî duyuruları tarihçeli kaydet; sadece endekse eklenme etiketinden otomatik alım sonucu üretme.",
            "sources": ["bist_calendar", "index_effect"],
        },
        {
            "id": "macro_balance_sheet",
            "title": "Makro sürpriz ve bilanço hassasiyeti",
            "priority": 6,
            "mechanism": "Faiz ve kur sürprizinin şirket etkisi borcun para birimi/vadesi, döviz gelirleri ve girdi maliyetlerine bağlıdır. Kur artışı tüm ihracatçıları aynı ölçüde desteklemez.",
            "evidence": "TCMB aktarım açıklaması beklenti, faiz, varlık fiyatı ve kur kanallarını tanımlar. TCMB'nin 1996–2010 firma çalışması döviz borcu ve düşük ihracat payıyla ilişkili kırılganlıkları inceler; güncel hisse getirisi stratejisini kanıtlamaz.",
            "required_data": ["Karar öncesi beklenti ve gerçekleşme", "Yayın tarihinde bilinen net döviz pozisyonu", "Faiz tipi, borç vadesi, ihracat ve ithal girdi payı"],
            "available": "Veri bağlantısı eksik",
            "falsifier": "Piyasa/sektör etkisi çıkarıldığında ayrışma kalmazsa veya model gelecekte yayımlanan bilanço bilgisine dayanıyorsa reddedilir.",
            "next_step": "Önce şirket hassasiyet haritası kur; açıklama tarihine bağlı veriyle makro olayları test et.",
            "sources": ["monetary_transmission", "fx_balance_sheet"],
        },
        {
            "id": "auction_liquidity",
            "title": "Mikroyapı ve müzayede likiditesi",
            "priority": 7,
            "mechanism": "Emir derinliği ve eşleşme dengesizliği fiyatın yeni emirlere hassasiyetini değiştirebilir. Günlük barlardan sıra önceliği, gizli emir veya gerçekleşebilir fiyat çıkarılamaz.",
            "evidence": "Farmer ve arkadaşları Londra Borsası emir olaylarında büyük fiyat değişimlerini likidite boşluklarıyla ilişkilendirir. Bu bulgu BIST müzayede stratejisine doğrudan kanıt değildir; ayrı veri ve deney gerekir.",
            "required_data": ["Lisanslı zaman damgalı emir defteri", "Müzayede gösterge fiyatı ve dengesizlik", "İşlem kısıtları, seans bilgisi ve gerçek gerçekleşmeler"],
            "available": "Veri bağlantısı eksik",
            "falsifier": "Sıra, gecikme ve kayma modele eklendiğinde avantaj kaybolursa veya sinyal işlem yapılabilir olmadan fiyatlanırsa reddedilir.",
            "next_step": "Önce yalnız gözlem ve gerçekleşme simülasyonu kur; günlük hacimden kurumsal emir veya gizli likidite tespiti iddia etme.",
            "sources": ["liquidity_gaps", "bist_rules"],
        },
    ],
    "roadmap": [
        "Tarih hizalama, veri bütünlüğü ve kurumsal işlem düzeltmelerini denetle; geçmiş evren yoksa sağkalım yanlılığını görünür tut.",
        "Üç sabit kuralı zaman sıralı %65/%35 ayrımla, ertesi açılış ve çakışmayan işlemlerle araştır; iki kat maliyet stresini ve betimsel yeniden örnekleme bantlarını birlikte göster. Bantları istatistiksel anlamlılık kanıtı sayma.",
        "Tahminleri üretildiği anda sürüm ve veri özetiyle kaydet; sonuçları gelecekte olgunlaştığında değerlendir. Geçmiş testini canlı başarı diye sunma.",
        "KAP, endeks akışı ve şirket bilançosu için yayın zamanına duyarlı veri bağlantıları kur; eksik bağlantı tamamlanmadan sinyal üretme.",
        "Bağımsız ileri dönem gözlemi, kapasite ve gerçek gerçekleşme kanıtı oluşana kadar bütün adayları araştırma statüsünde tut.",
    ],
    "rejected": [
        "Kesin kazanç, kusursuz tahmin veya piyasanın kalıcı arka kapısı iddiası.",
        "Gelecek veri sızıntısı, aynı kapanıştan gerçekleşme ve sonradan seçilmiş kazanan stratejiler.",
        "Temettü/bölünme kaynaklı fiyat değişimini bilgi avantajı saymak veya hacmi yatırımcı kimliği olarak yorumlamak.",
        "Farklı ülkelerdeki tarihsel bulguları sınamadan BIST avantajı diye aktarmak; eksik veri yerine tahmin uydurmak.",
    ],
    "sources": [
        {"id": "trading_costs", "title": "Frazzini, Israel & Moskowitz — Trading Costs of Asset Pricing Anomalies", "url": "https://www.aqr.com/Insights/Research/Working-Paper/Trading-Costs-of-Asset-Pricing-Anomalies", "scope": "1998–2011, 19 gelişmiş piyasa; gerçek kurumsal işlemler. BIST maliyet tahmini değildir."},
        {"id": "momentum_crashes", "title": "Daniel & Moskowitz — Momentum Crashes", "url": "https://www.sciencedirect.com/science/article/pii/S0304405X16301490", "scope": "2016 araştırması; uluslararası momentumun düşüş sonrası toparlanma riski. Yerel uzun pozisyon kuralının doğrulaması değildir."},
        {"id": "earnings_attention", "title": "DellaVigna & Pollet — Investor Inattention and Friday Earnings Announcements", "url": "https://sdellavi.com/pdf/earnfr080204.pdf", "scope": "1995–2006 bilanço açıklamaları; sınırlı dikkat mekanizması. BIST kanıtı değildir."},
        {"id": "bist_calendar", "title": "Borsa İstanbul — Endeks Dönemsel Takvimleri", "url": "https://www.borsaistanbul.com/endeksler/endeks-donemsel-takvimleri", "scope": "Resmî dönem ve ilan takvimi; tek başına fiyat etkisi veya getiri kanıtlamaz."},
        {"id": "index_effect", "title": "Greenwood & Sammon — The Disappearing Index Effect", "url": "https://www.hbs.edu/ris/Publication%20Files/23-025_563e45c6-df92-4d9c-ae05-608d4d0acab1.pdf", "scope": "Kasım 2023 revizyonu; S&P 500 etkisinin zamanla azalması. Güncel BIST tahmini değildir."},
        {"id": "monetary_transmission", "title": "TCMB — Para Politikası ve Enflasyon", "url": "https://www.tcmb.gov.tr/wps/wcm/connect/TR/TCMB%2BTR/Main%2BMenu/Temel%2BFaaliyetler/Para%2BPolitikasi/Fiyat%2BIstikrari%2Bve%2BEnflasyon/PP%2BEnflasyon", "scope": "Resmî aktarım kanalları açıklaması; yön veya kazanç sinyali değildir."},
        {"id": "fx_balance_sheet", "title": "Alp & Yalçın — Borç Dolarizasyonu ve Büyüme Performansı, TCMB 15/01", "url": "https://www.tcmb.gov.tr/wps/wcm/connect/EN/TCMB%2BEN/Main%2BMenu/Publications/Research/Working%2BPaperss/2015/15-01", "scope": "1996–2010 Türkiye firma verisi; bilanço kanalı. Güncel pay getirisi modeli değildir."},
        {"id": "liquidity_gaps", "title": "Farmer ve arkadaşları — What Really Causes Large Price Changes?", "url": "https://arxiv.org/abs/cond-mat/0312703", "scope": "2004 revizyonu, Londra Borsası emir olayları; likidite boşlukları. BIST müzayede kanıtı değildir."},
        {"id": "bist_rules", "title": "Borsa İstanbul — Pay Piyasası İşleyişi", "url": "https://borsaistanbul.com/piyasalar/pay-piyasasi/piyasa-isleyisi", "scope": "Resmî seans, emir, fiyat limiti ve tedbir çerçevesi. Tarihsel pay bazlı gerçekleşme kuralları ayrıca gereklidir; güncel açığa satış yetkisi varsayılmaz."},
        {"id": "multiple_testing", "title": "Harvey, Liu & Zhu — The Cross-Section of Expected Returns", "url": "https://www.nber.org/papers/w20592", "scope": "Çok sayıda faktör denemenin yanlış keşif riski; sıradan anlamlılık eşikleri yeni strateji kanıtı için yeterli değildir."},
        {"id": "bist_history", "title": "Borsa İstanbul — Geçmişe Dönük Veri Satışı", "url": "https://www.borsaistanbul.com/veriler/gecmise-donuk-veri-satisi", "scope": "Resmî tarihsel veri edinme kanalı. Bu uygulamada lisanslı veri bağlantısının kurulduğu anlamına gelmez."},
    ],
}
